name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan \
          -var "confluent_cloud_api_key=${{ secrets.CONFLUENT_CLOUD_API_KEY }}" \
          -var "confluent_cloud_api_secret=${{ secrets.CONFLUENT_CLOUD_API_SECRET }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform apply -auto-approve -var '"confluent_cloud_api_key=${{ secrets.CONFLUENT_CLOUD_API_KEY }}"' -var '"confluent_cloud_api_secret=${{ secrets.CONFLUENT_CLOUD_API_SECRET }}"'